services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/data:/app/data
    env_file:
      - ./.env
    environment:
      - MODEL_API_URL=http://model:8000/predict
      - REDIS_URL=redis://redis:6379
    depends_on:
      - model
      - redis

  model:
    image: ntise/lungscan-api:cpu
    ports:
      - "8001:8000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
