export { default as AuthPage } from './AuthPage'
export { default as ResetPasswordPage } from './ResetPasswordPage'
export { default as DoctorPage } from './DoctorPage'
export { default as AdminPage } from './AdminPage'
export { default as UploadPage } from './UploadPage'
export { default as ScansPage } from './ScansPage'
